### ISSUE TITLE
Tests not discovered when py.test is enabled

### ISSUE THREAD

**Issue by ralexx** [DonJayamanne/pythonVSCode#307]
@DonJayamanne, thanks for your responsiveness on reports/requests.

VSCode 1.5.2/Python 0.3.22 does not discover my py.test unit tests. What am I missing?

* `pytest` is installed in my conda environment
* `python.unitTest.pyTestEnabled` set to true in `settings.json`
* `code .` is launched with that environment activated, from the root directory of my package (screen shots below)
* I can run the tests from the same environment/directory using a separate terminal

![settings](https://cloud.githubusercontent.com/assets/6756310/18462478/7b9c2c3c-7937-11e6-877d-7e770c5d8cae.png)

![settings2](https://cloud.githubusercontent.com/assets/6756310/18462593/6527a4b2-7938-11e6-84c1-76fdb7b71b44.png)

```shell
⋊> ~/r/f/indexdata on new_subportfolios ⨯ py.test tests/test_indexes.py
============================= test session starts ==============================
platform darwin -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /Users/ralex/repos/fin-econ/indexdata, inifile:
plugins: cov-2.3.1, xdist-1.14
collected 61 items

tests/test_indexes.py x............................x....................F..xF......
```

**Comment by DonJayamanne** [comment]
You will need to configure pytest to tell it where your tests are located. Just as you have done in the above terminal window (if you look above you're providing the file name).

You could either provide the arguments in settings.json or create a pytest.ini file.
Instructions can be found [here](https://github.com/DonJayamanne/pythonVSCode/wiki/pytest-Framework#configuration-options)

The easier options is to just create a pytest.ini file as follows:
```ini
# content of pytest.ini
[pytest]
testpaths = tests
```

**Comment by DonJayamanne** [comment]
@ralexx  Sorry for closing, should have waited for a confirmation.
Let me know if you have any other issues.

**Comment by ralexx** [comment]
@DonJayamanne , Thank you for clarifying. I reviewed your notes when I was setting up but I didn't understand that the test path had to be passed explicitly. This differs from pytest [expected behavior](http://docs.pytest.org/en/latest/goodpractices.html#test-discovery): 

> If no arguments are specified then collection starts from testpaths (if configured) or the current directory...[then] recurse[s] into directories..."

In the example case above I happened to be running a single test module but `py.test` with no arguments also works from the command line due to built-in recursive discovery. I don't use a `pytest.ini` file for this code.

Can your implementation of the call to pytest preserve standard test discovery? If not, it would help to specify in the wiki that test path and/or filename must be specified in `pytest.ini` (likely the preferable case) or passed as args in `settings.json`. I'm happy to suggest some text.

**Comment by ralexx** [comment]
Very nice having integrated testing. I don't see code lenses above my test classes but otherwise it works nicely. Awesome.

**Comment by DonJayamanne** [comment]
@ralexx , you are simply awesome. You've done all of the hard yards for me. Thanks, will get a fix out ASAP, as this was one of the major features of this new release, already released a build with fixes yesterday.

Anyways, thanks again.

**Comment by DonJayamanne** [comment]
@ralexx 
>I don't see code lenses above my test classes but otherwise it works nicely. Awesome.
Unfortunately you're seeing the cached code lenses. The unit tests were discovered after you opened the file. If you make a change to the file (add an empty space), then the code lens will be visible. If not please do raise it as an issue.

I do plan on refreshing the code lenses once unitests have been discovered. However this is an upstream (VS Code) issue/change.

**Comment by gandhis1** [comment]
I'm having a few issues with this, want to make sure I understand the current behavior.

I am using pyTest. Within a sub-sub-directory of the open folder, I have at least 1 file which begins with "test_", and a function within that file exists which similarly begins with "test_". 

Is the extension supposed to be able to search recursively for these tests? Do I need to explicitly specify them? If so, why? Why can't it discover the tests automatically?

I ask this, because at least a couple weeks ago, the extension *was* discovering my tests and *was* able to run them. However - now, when I start up VSCode, it says there are no tests. However, if I attempt to run the tests by invoking the command "Run All Unit Tests", it does work, and it does identify the test. This behavior sounds like a bug to me, because the extension should be able to discover all tests before I attempt to run any.

**Comment by ralexx** [comment]
@gandhis1 

Since you were getting the expected behavior previously, I assume you've checked that `settings.json` still shows `"python.unitTest.pyTestEnabled": true`, other  `"python.unitTest` settings are `false`, you have deleted `.cache` from your module's root directory, and that you've activated any virtualenv or condo env before running VSCode. I'm running Python plugin v0.5.0 and VSCode 1.6.1 and my tests are discovered.

> Is the extension supposed to be able to search recursively for these tests?

The extension is supposed to *support* recursive test search, which is a standard `py.test` feature. I'm not familiar with TypeScript so I can't tell if the plugin handles the path specification itself or simply calls `py.test`. The distinction should be transparent to users.

> Do I need to explicitly specify them?

No, not if you can run `py.test` at the command line from the root directory of your module and py.test discovers your tests.

> Why can't it discover the tests automatically?

It might help @DonJayamanne answer that question if you list your OS, VSC and plugin version numbers.

**Comment by DonJayamanne** [comment]
@gandhis1 
Apologies for not getting back. Please re-open the issue if it persists.
Will look into this now, been working on unitests the past few days.

**Comment by DonJayamanne** [comment]
@gandhis1 
Yes, identified the problem. Was fixed in py.test a few days ago as well.  
If there's one file, then it isn't identified.

**Comment by gandhis1** [comment]
Thanks, will give it a shot when the next extension update comes out, and report back if I still have any troubles

**Comment by OsirisTerje** [comment]
I've just  tried to enable the pytest, but are rewarded by this, nearly regardless of any setting changes I try to do:
![image](https://user-images.githubusercontent.com/203432/29693096-fa5c9c16-8933-11e7-847f-547897731a6d.png)
I have enabled pytest, and made sure the others are off. 
I have added the extra arguments to the pytest arguments, just to be sure (can't see how they can affect this, but)
I have also specifically added the paths to the python and pytest.

If I run from command line, all works.
![image](https://user-images.githubusercontent.com/203432/29693135-456c0796-8934-11e7-9444-f6f3d59e0a92.png)

This is just a very simple test program, just to get the environment up and running.
![image](https://user-images.githubusercontent.com/203432/29693207-a1b12162-8934-11e7-80b3-6cd1bb36196f.png)

The extension version 0.7.0.

Is there some regression here?

**Comment by DonJayamanne** [comment]
Please could you open the python tests output panel (drop down bottom left along with tasks, gt, etc) and tell me what's in there when you get this error. 

Also what are the contents of your python settings. What arts have you added. What is your is and python interpreter.

**Comment by DonJayamanne** [comment]
Oh yes, what's the name of this python test file? And what directory is it listed on?

**Comment by jbarlow83** [comment]
@DonJayamanne  I get this discovery error with pytest as well - very consistently.

The error message is "There was an error in discovering tests, please check the configuration settings for the tests."

I have pytest in a virtual environment. 
```
{
    "python.pythonPath": "${workspaceRoot}/venv/bin/python3",
    "python.venvPath": "${workspaceRoot}/venv",
    "restructuredtext.builtDocumentationPath" : "${workspaceRoot}/docs/_build/html",
    "restructuredtext.confPath"               : "${workspaceRoot}/docs",
    "restructuredtext.updateOnTextChanged"    : "true",
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/venv/lib": true,
        "**/venv/share": true,
        "**/.idea": true,
        "docs/_build/**": true,
        "**/.sublime*": true
    },
    "files.associations": {
        "memory": "cpp",
        "algorithm": "cpp",
        "variant": "cpp"
    },
    "python.unitTest.pyTestArgs": [],
    "python.unitTest.pyTestEnabled": true,
    "python.unitTest.pyTestPath": "tests",
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.unittestEnabled": false
}
```

The output panel of "Python Test Log" during test discovery says:
```
undefined
Test Disovery failed: 
TypeError: Cannot read property 'split' of undefined
Error: Error: spawn tests ENOENT
Test Disovery failed: 
Error: spawn tests ENOENT
Test Disovery failed: 
Error: spawn EACCES
```

Seems related to this node.js issue: https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

I suspect that VS Code is not taking the Python virtual environment into account when attempting to invoke pytest.

VS Code also complains that "Pytest Framework is not installed". Clicking install while run `pip3 install pytest` which succeeds.

This is using Python extension 0.7.0. The tests are in the "tests" folder.

Test configuration is in setup.cfg. I tried a pytest.ini and that does not work. Also tried cache. Also replicated in another project. Executing `pytest` within the VS Code terminal works fine.

**Comment by Kurara** [comment]
I have the same problem but with:
"python.unitTest.unittestEnabled": true

I can execute all tests, but not single ones. And I can't debug :(

**Comment by daniel-yang-apijet** [comment]
if you hover over `pyTestPath` it says

> Path to pytest (pytest), you can use a custom version of pytest by modifying this setting to include the full path.

I put the path to pytest (with virtualenv path) for my path and it worked (mostly, still doesn't detect tests). For example, `/Users/name/VEs/venv/bin/pytest`
