### ISSUE TITLE
Extract Method Fails: string index out of range

### ISSUE THREAD

**Issue by vossad01** [DonJayamanne/pythonVSCode#363]
Attempting to the Extract Method Refactor with the code shown below fails with the following error.
>Cannot perform refactoring using selected element(s). (Refactor failed. string index out of range [sic: lack of `)`]

For it to fail, you must include the last line show in the code below in the code to be extracted.  When I have the same class not isolated to its own file, I get the same error even with some of the other lines.

test.py:
```python
class Test:
    def myThing(self):
        line = ["hi"]
        piece = ""
        copy = list(line)
        copy[0] = piece
```

Python Console output:
```
Traceback (most recent call last):
  File "refactor.py", line 245, in watch
    self._process_request(self._input.readline())
  File "refactor.py", line 234, in _process_request
    request['start']), int(request['end']), request['name'])
  File "refactor.py", line 195, in _extractMethod
    refactor.refactor()
  File "refactor.py", line 89, in refactor
    self.onRefactor()
  File "refactor.py", line 152, in onRefactor
    self.project, self.resource, self._startOffset, self._endOffset)
  File "C:\Users\user\.vscode\extensions\donjayamanne.python-0.3.24\pythonFiles\rope\refactor\extract.py", line 79, in __init__
    super(ExtractMethod, self).__init__(*args, **kwds)
  File "C:\Users\user\.vscode\extensions\donjayamanne.python-0.3.24\pythonFiles\rope\refactor\extract.py", line 43, in __init__
    self.end_offset = self._fix_end(resource.read(), end_offset)
  File "C:\Users\user\.vscode\extensions\donjayamanne.python-0.3.24\pythonFiles\rope\refactor\extract.py", line 51, in _fix_end
    while offset > 0 and source[offset - 1].isspace():
IndexError: string index out of range
```

**Comment by DonJayamanne** [comment]
@vossad01 , please ensure you have a blank line at the end.
Updated vs code to display a message accordingly.

```python
1. class Test:
2.     def myThing(self):
3.         line = ["hi"]
4.         piece = ""
5.         copy = list(line)
6.         copy[0] = piece
7. 
```

**Comment by DonJayamanne** [comment]
@vossad01 , new release has been published with the fix.

**Comment by vossad01** [comment]
Thanks Don!  Unfortunately, the update didn't seem to fix this for me.

I updated the extension. No change.
Restarted VSC. Not change.
Updated VSC. No change.

Here is a screenshot showing the error, my extension version, and that I have a blank line at the end.  Even before I had the update, blank lines at the end made no difference.

![capture](https://cloud.githubusercontent.com/assets/965439/19254571/83fd92a0-8f1a-11e6-9b87-50a00d3c1822.PNG)

Here is the Traceback:
```
Traceback (most recent call last):
  File "refactor.py", line 266, in watch
    self._process_request(self._input.readline())
  File "refactor.py", line 255, in _process_request
    request['start']), int(request['end']), request['name'])
  File "refactor.py", line 212, in _extractMethod
    refactor.refactor()
  File "refactor.py", line 89, in refactor
    self.onRefactor()
  File "refactor.py", line 152, in onRefactor
    self.project, self.resource, self._startOffset, self._endOffset)
  File "C:\Users\user\.vscode\extensions\donjayamanne.python-0.4.0\pythonFiles\rope\refactor\extract.py", line 79, in __init__
    super(ExtractMethod, self).__init__(*args, **kwds)
  File "C:\Users\user\.vscode\extensions\donjayamanne.python-0.4.0\pythonFiles\rope\refactor\extract.py", line 43, in __init__
    self.end_offset = self._fix_end(resource.read(), end_offset)
  File "C:\Users\user\.vscode\extensions\donjayamanne.python-0.4.0\pythonFiles\rope\refactor\extract.py", line 51, in _fix_end
    while offset > 0 and source[offset - 1].isspace():
IndexError: string index out of range
```

**Comment by vossad01** [comment]
@DonJayamanne
I doubt OS is relevant to this, but I confirm this occurs under Linux as well as Windows.  Just tested on Linux with VSC 1.6.1 and version 0.5.0 of this extension.

**Comment by DonJayamanne** [comment]
@vossad01 
What version of Python are you using?

**Comment by vossad01** [comment]
Windows: 2.7.9
Linux: 2.7.12

**Comment by DonJayamanne** [comment]
Fixed
https://github.com/DonJayamanne/pythonVSCode/commit/7afece65dbb4becc8e41dc2e759a492c4b18255e

**Comment by vossad01** [comment]
@DonJayamanne I still see this on 0.5.1 and 0.5.2, though GitHub indicates that commit is included in both.  The output is a bit different though:

>##########Refactor Output##########
Error in refactoring:
Refactor failed. string index out of range
[('refactor.py', 266, 'watch', 'self._process_request(self._input.readline())'), ('refactor.py', 255, '_process_request', "request['start']), int(request['end']), request['name'], int(request['indent_size']))"), ('refactor.py', 212, '_extractMethod', 'refactor.refactor()'), ('refactor.py', 89, 'refactor', 'self.onRefactor()'), ('refactor.py', 152, 'onRefactor', 'self.project, self.resource, self._startOffset, self._endOffset)'), ('/home/vossad01/.vscode/extensions/donjayamanne.python-0.5.2/pythonFiles/rope/refactor/extract.py', 79, '__init__', 'super(ExtractMethod, self).__init__(*args, **kwds)'), ('/home/vossad01/.vscode/extensions/donjayamanne.python-0.5.2/pythonFiles/rope/refactor/extract.py', 43, '__init__', 'self.end_offset = self._fix_end(resource.read(), end_offset)'), ('/home/vossad01/.vscode/extensions/donjayamanne.python-0.5.2/pythonFiles/rope/refactor/extract.py', 51, '_fix_end', 'while offset > 0 and source[offset - 1].isspace():')]
