### ISSUE TITLE
Linting with pylint failed warning

### ISSUE THREAD

**Issue by Botong** [DonJayamanne/pythonVSCode#7]
After updating to 0.1.1, I started to get warning says:"Linting with pylint failed. If not installed please turn if off in settings. View Python output for details." 

my Linting is set to be on and pylint is installed.

**Comment by DonJayamanne** [comment]
Please could you check the output for Python. Use the command toggle output, and select python from the  drop down. Let me know what is in there. Thanks. Fyi, it is working for me on my Mac and Windows.

**Comment by dbw9580** [comment]
I'm having a similar problem: I have python and pep8 installed in the cygwin bin folder but VS Code complains these:
`Linting with pep8 failed. If not installed please turn if off in settings.
 Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\cygwin64\bin\pep8  --format='%(row)d,%(col)d,%(code)s,%(code)s:%(text)s' d:\dbw\Projects\pyytcrawler\populate.py"`
Apparently cmd failed to identify pep8 as a python script and thus could not execute it.
Is there a way to let VS Code know to execute certain commands with cygwin's shell interpreter?

**Comment by DonJayamanne** [comment]
Please could you confirm that pep is a python script for and not an exe. If that is the case then you might have too prefix pep8 path with their path to python. Eby. "C:\python\python.exe c:\cygwin..pep8. Etc..." This can done in the settings file when setting the fully wualifued path to pep.

**Comment by DonJayamanne** [comment]
Apologies for the typo, using my phone at this moment, wualifued is meant to read qualified. Hope the rest makes sense.

**Comment by Botong** [comment]
The following is what I found in python output console

Linting with pylint failed. If not installed please turn if off in settings.
 No config file found, using default configuration

2016-01-30 21:44 GMT+08:00 DonJayamanne <notifications@github.com>:

**Comment by DonJayamanne** [comment]
I believe I know the cause to your (Botong) issue. Please bear  with me for a day and it will be resolved. Sorry for the inconvenience.

**Comment by DonJayamanne** [comment]
Hi Boton, the issue has been fixed in the new release. Please test and let me know. Once again sorry for the inconvenience.

**Comment by dbw9580** [comment]
Hi,
I specified the path to the python executable and pylint got executed. However, linting still failed due to cygwin path problem:
`Linting with pylint failed. If not installed please turn if off in settings.`
`Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\cygwin64\bin\python2.7.exe C:\cygwin64\bin\pylint  --msg-template='{line},{column},{category},{msg_id}:{msg}' --reports=n --output-format=text d:\dbw\Projects\pyytcrawler\populate.py"`
`No config file found, using default configuration`
`Traceback (most recent call last):`
`  File "C:\cygwin64\bin\pylint", line 11, in <module>`
`    sys.exit(run_pylint())`
`  File "/usr/lib/python2.7/site-packages/pylint/__init__.py", line 23, in run_pylint`
`    Run(sys.argv[1:])`
`  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 1313, in __init__`
`    linter.check(args)`
`  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 734, in check`
`    self._do_check(files_or_modules)`
`  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 865, in _do_check`
`    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)`
`  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 923, in check_astroid_module`
`    tokens = utils.tokenize_module(ast_node)`
`  File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 151, in tokenize_module`
`    with module.stream() as stream:`
`  File "/usr/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 389, in stream`
`    return self._get_stream()`
`  File "/usr/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 374, in _get_stream`
`    stream = open(self.source_file, 'rb')`
`IOError: [Errno 2] No such file or directory: '/cygdrive/d/dbw/Projects/pyytcrawler/d:\\dbw\\Projects\\pyytcrawler\\populate.py'`

Also, similar problem occurs when clicking 'Go to definition' on some var name, says the file does not exists. The path to the file is Windows style.
I guess VS Code is just not compatible with cygwin at this moment.

**Comment by DonJayamanne** [comment]
Hi please could you update to the latest version. The first part off the issue may have been resolved, I say may because I believe you are experiencing an issue that is similar to what was fixed.

**Comment by DonJayamanne** [comment]
As for the paths, I believe this can be fixed and is most likely a problem with my code. I need to parse the text and get the actual widows file path. So even if you do install the latest version, the message would be different, but the root problem of not being able to parse the path would still exist. Par give me a few days to figure this out.

**Comment by DonJayamanne** [comment]
I say a few days because this is fairly new to me (chain on Windows), Guess I will have to learn this to resolve this issue.

**Comment by DonJayamanne** [comment]
Chain on Windows = cygwin on Windows, you gotta love autocorrect. 😄

**Comment by dbw9580** [comment]
Thanks for the update.
I know cygwin on windows can be tricky so great thanks.

**Comment by Botong** [comment]
Thank you, this is fixed in the latest release

**Comment by KiritoStudio** [comment]
Hi, I have the same error on my Macbook. I'm new in OSX, so could you please tell me how to trace and fix the error? Many thx.
![image](https://cloud.githubusercontent.com/assets/553215/16356284/007f42ac-3b05-11e6-9072-2f9139bac5fa.png)
