### ISSUE TITLE
Go To Definition of decorated functions in package goes to the decorator

### ISSUE THREAD

**Issue by PeterJCLaw** [DonJayamanne/pythonVSCode#742]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   2.7.12
OS and version:   Ubuntu 16.04

## Actual behavior

Navigating to definition of a decorated function shows the definition of the decorator.

Note: this only reproduces in a package and not in a single file.

In one sense I can see why this is happening -- the decorator is actually what the symbol in question really _is_. However, that is not a useful thing for an editor to do and I would _much_ prefer to be shown the definition of the decorated function instead.

I believe this is also a regression as I've only noticed this behaviour recently (I _think_ it started failing some time after the new year, but I'm not sure).

## Expected behavior

Navigating to definition of a decorated function should show the function in question.

## Steps to reproduce:
- Create a package with a decorated function in one file and a usage of that function in another. I've put an example at https://gist.github.com/PeterJCLaw/38b39e6ee7bfa0cd69e00ce984aebde3.
- Open VSCode to the directory containing the above files
- Open the usages file
- Navigate to the definition of the `my_context_manager` function from either the import or the usage (I use Ctrl+Click, though F12 and the context menu also reproduce the issue)
- Will navigate to the wrong place

This issue shows up for both class- and function-based decorators and for both local and standard-library decorators.

## Settings  
Reproducible with defaults.

## Logs
None.

**Comment by zackkitzmiller** [comment]
@DonJayamanne Any idea on a timeline for a fix here? I'd love to contribute but don't know my way around TypeScript.

**Comment by PeterJCLaw** [comment]
I had a go at debugging this, but didn't get very far. I managed to just about get a debug setup where I could step through the Python code which was actually doing the code understanding, but didn't feel I was getting very far with actually diagnosing the problem.

@DonJayamanne:
- I found that getting going with stepping through the code was quite hard, is there a how-to that I've overlooked?
- I see you've added the "upstream" label to this. Presumably this means that you believe this is an issue in the jedi project used for the actual code understanding. Is there an upstream bug I should look at to track/help?
- Are there some notes somewhere on how the copies of jedi in this repo differ from the upstream and why?

**Comment by PeterJCLaw** [comment]
Note: I'm suspicious that this and #781 are related.

**Comment by zackkitzmiller** [comment]
One this to note is that this is a regression. Everything was working properly before something about 0.5.7.

**Comment by mpoindexter** [comment]
This seems to be because the extension uses goto_definitions instead of goto_assignments when calling Jedi.  Calling goto_assignments instead fixes this, but changes the behavior when going to an imported function.

i.e. with the current code clicking on `bar` in this code
```
from foo import bar

bar()
```
will jump to `bar` in the `foo` module, but if goto_assignments is used this will jump to the `from foo import bar` line.

**Comment by gandhis1** [comment]
I would argue that the latter is more correct. The import statement *is* the definition of said variable.

**Comment by PeterJCLaw** [comment]
@mpoindexter Thanks for that insight; I'm not sure how it relates to this bug specifically though. Are you suggesting, as I think @gandhis1 is, that avoiding the decorator issue entirely by only going to the import statement is a suitable fix here? (If so, I disagree!)

@gandhis1 That's true, though I'm not convinced that that's the most useful thing when you hit F12 in the editor.

While I don't really want to go too far down the road of redefining how the IDE behaves, I do think there's value in collecting descriptions of the behaviours we do want so that it's clear what behaviour we're aiming for when working on bugs in this area. (From what @mpoindexter noted about jedi, it seems likely that both this bug and #781 are results of the same underlying jedi behaviour).

Summarising what I think I'd want the IDE to do:
- Where a symbol is assigned (e.g: `Foo = namedtuple('Foo', ('x', 'y'))`, I want to go to the assigning statement. (I think I want this for all assignments, whether local or the other side of an import and whether the result of a constant assignment, function call or class construction; are there other cases I've missed?)
- Where a symbol is decorated, I want to go to the definition of the undecorated symbol (ideally with the decorating lines scrolled into being visible)
- For a plain function or class definition I want to be shown that definition
- From the usage of an import (whether renamed or not), I want to be taken to the definition of that entity in the imported module. If it's an indirect import, such as via a `__init__.py`, I want to go to the original rather than intermediate definition. That is, the IDE should recursively follow imports until a non-import definition of the symbol is found.

**Comment by mpoindexter** [comment]
@PeterJCLaw it relates to this bug specifically because goto_definitions is supposed to behave exactly this way (see https://github.com/davidhalter/jedi-vim/issues/348). In that discussion, the author of Jedi suggests to use goto_assignments instead of goto_definitions for this use case, and I was just pointing out the downsides of switching to goto_assignments.

It seems like goto_assignments has acquired a flag called follow_imports that purports to behave exactly as you describe this should work (and I agree with), but it seems broken in the latest Jedi.  I filed a bug there https://github.com/davidhalter/jedi/issues/945, and suggested some code that seems to solve the problem.

**Comment by PeterJCLaw** [comment]
@mpoindexter Aha, that makes sense; I'd not seen https://github.com/davidhalter/jedi-vim/issues/348.

Following the conversation from that issue leads to https://github.com/davidhalter/jedi/issues/604, which looks like it's related to this as well.

**Comment by PeterJCLaw** [comment]
Since version 0.7.0 and VSCode version 1.15.0 this appears fixed, but I haven't seen anything in the release notes which looks related.

**Comment by DonJayamanne** [comment]
Thanks, will update the release notes. Yes this has been fixed, should be on release notes of older version.

**Comment by DonJayamanne** [comment]
Will double check the release notes

**Comment by jipengzhu** [comment]
I have the same problem still now  ( vscode version 1.24.1 (1.24.1))


when i want to jump to the `search method` in `Elasticsearch class`

it navigates me to the location of decorator method


 ![image](https://user-images.githubusercontent.com/29984300/41399212-4e598faa-6fec-11e8-9048-b14bcc786a42.png)

![image](https://user-images.githubusercontent.com/29984300/41399315-91858568-6fec-11e8-8ac8-8bff69018f91.png)

**Comment by zackkitzmiller** [comment]
Yup. This regressed.

**Comment by bcroq** [comment]
I get this regression too.

**Comment by bcroq** [comment]
@PeterJCLaw glad to hear this regression should be fixed soon. Thanks.

**Comment by jipengzhu** [comment]
@PeterJCLaw ok and 3Q 😀
