### ISSUE TITLE
Error message "Linter pylint is not installed" persists after "Disable this linter" is clicked

### ISSUE THREAD

**Issue by kieferrm** [DonJayamanne/pythonVSCode#763]
Moved from https://github.com/Microsoft/vscode/issues/16796. See discussion there for details.

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. Open a .py file.
2. Open another .py file, add something and save.
3. Error "Linter pylint is not installed" appears.
4. Click on "Disable this Linter"
5. Edit the file again and save.
6. Error "Linter pylint is not installed" appears AGAIN.

Note.
Close and restart VS Code does not solve the issue.
I don't want pylint (it is too noisy).

Thanks,
Alessandro

**Comment by DonJayamanne** [comment]
@alex75it, @mohamed-elsaka, @MahonyCZ13 @bighomeyg @sid8128 @NableLucas 
Hi guys, I am unable to replicate this issue at my end under one particular condition, that's without having a folder (workspace) open. 
I would like to confirm this is the only scenario under which this occurs.

Do you have a folder (workspace) opened when this message is displayed  promp

**Comment by DonJayamanne** [comment]
@alex75it, @mohamed-elsaka, @MahonyCZ13 @bighomeyg @sid8128 @NableLucas
Hi everyone, this issue has been fixed in the development branch and the fix will be available in the next release (sometime next week).

Apologies for the annoying issue, I haven't come across this issue, not untill today, simply because I haven't tested nor used VS Code without opening a folder.

**Comment by Wubians** [comment]
I'm still getting this with v0.5.9

**Comment by iiedii** [comment]
I still have this problem with v0.5.9 and WITH a folder opened as well.

**Comment by iiedii** [comment]
OK. #793 may be the cause of this issue.

**Comment by florenthemmi** [comment]
Same here with `VS Code 1.10.2` and `pythonVSCode 0.5.9` .

**Comment by DonJayamanne** [comment]
Please could you check if anything is logged here:  
- ```Python``` output panel  
- ```Console``` window in ```Help->Developer Tools```

**Comment by DonJayamanne** [comment]
You can always manually disable it by adding the following setting into the ```settings.json``` file:  
```json
"python.linting.enabled": false
```

**Comment by iiedii** [comment]
In my case, it is very weird. It simply says "Linter pylint is not installed" while it indeed is installed pretty well.

The output panel is empty. Helper -> Developer Tools just reports the problem as it is:
`Linter pylint is not installede.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98`

Looks nothing more helpful. Yeah, I have to disable it in development. Is there any other debugging info I can help provide?

**Comment by iiedii** [comment]
Ahhh... solved. I manually set the python path in File >> Preference >> Settings.
"python.pythonPath" defaulted to "python" in my case. I didn't know where it exactly pointed to. I manually edited it with the absolute path. Problem solved. Note that I installed only one version of Python (2.7.13), and had the environmental variable %PATH% set. Just couldn't understand why it didn't automatically find the correct path.

**Comment by boydthomson** [comment]
resolved this issue on VS Code for linux by changing:
"python.linting.pylintPath": "pylint"
to
"python.linting.pylintPath": "pylint3"

**Comment by agdfoster** [comment]
I have this problem again after a recent vscode update.
Saying "is not installed" when it is.
Tried @boydthomson 's solution, no avail.

Console logs:

Linter pylint is not installed
e.doShow @ messageService.ts:125

and potentially unrelated:

Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at FinderController.readFilesIfChangedEditor (/Users/alexfoster/.vscode/extensions/takas-ho.unittest-switcher-0.1.3/out/src/FinderController.js:23:36)
    at FinderController._onEvent (/Users/alexfoster/.vscode/extensions/takas-ho.unittest-switcher-0.1.3/out/src/FinderController.js:20:14)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:55860)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:57651)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:388682
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:55860)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:57651)
    at t.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:345325)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308956)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189275)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189930)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by jdforsythe** [comment]
I had this problem and it seems to be a catchall message for any error from pylint.

First issue was a problem with the format of `.pylintrc`. I found this by just running `pylint` from the command line in my project folder.

Second issue was I was missing the pylint-django plugin. I found this by going to the "Output" tab under "Python" and copying the command it was trying to run, and then running it myself on the command line. The error told me it couldn't find `pylint-django` so I ran `pip install pylint-django` and it worked fine after that.

The takeaway is that the error shows even if you have pylint installed, it's just a catch-all message for any possible error causing a non-zero exit for pylint.

**Comment by Sti2nd** [comment]
Having the same problem now on Ubuntu with python2.7. Pylint is installed, still get the message. 
What command where you trying to run @jdforsythe ? I just get the usual messages, nothing seem to be wrong

**Comment by wolfgang-noichl** [comment]
Thanks @jdforsythe for the hint that any pylint error would trigger that.
As for me, running `pylint ./pyfile.py && echo 'worked'` revealed that missing modules can cause this message as well.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/1120
