### ISSUE TITLE
Debugging unittest tests doesn't work

### ISSUE THREAD

**Issue by yRefl3x** [DonJayamanne/pythonVSCode#797]
## Environment data
VS Code version:  1.10.1
Python Extension version:  0.5.9
Python Version:   2.7.5
OS and version:    Windows 10

## Actual behavior
After clicking on the "Debug Test" lens of a test method, debugging doesn't start. "Running Tests" is displayed at the bottom of the VSCode window indefinitely.
## Expected  behavior
Debugging starts.
## Steps to reproduce:  
I have the following folder structure:
```
Issue
    cool_package
        __init__.py
        cool_module.py
    test
        __init__.py
        test_cool_module.py
```
### cool_module.py
```
def foo(a, b):
    return a + b
```
### test_cool_module.py
```
import unittest

from cool_package.cool_module import foo

class TestCoolModule(unittest.TestCase):
    def test_foo(self):
        res = foo(1, 2)
        self.assertEquals(res, 3)
```

- Set a breakpoint at line ```res = foo(1, 2)```
- Click "Debug Test" in test method code lens

## Settings  
settings.json:   
```
{
    "python.unitTest.unittestArgs": [
        "-v",
        "-s",
        "test",
        "-p",
        "test_*.py"
    ],
    "python.unitTest.unittestEnabled": true
}
```   
## Logs
Output from ```Python Test Log``` output panel  
```
READY
```

**Comment by syagev** [comment]
Same exact symptoms here.
win10, python ext 0.6.0, VSC 1.10.2, Python 3.5.3

**Comment by yRefl3x** [comment]
@syagev I just tried reloading the window before debugging as you suggested. The test actually runs, but it doesn't debug. The breakpoint just changes to a grey circle for a short time but execution isn't stopped. The test just runs like when choosing "Run Tests"

**Comment by alexwhittemore** [comment]
Confirmed, but I can't try "reload window" to solve it, because "discovering tests" has stopped completing for me.

**Comment by gpassero** [comment]
I can debug tests when I run them with the following command line (in the end of the test file script). It may be a temporary solution for you.

```
if __name__ == '__main__':
    unittest.main()
```

**Comment by alexwhittemore** [comment]
Update: I can get unit tests to discover if I run "discover unit tests," then, while it works, run "run all tests," which causes discovery to alert failure. At this point, I can "run unit tests", which will trigger discovery successfully. At least, I think that's the flow. Will verify back at a computer.

**Comment by xqliu** [comment]
@alexwhittemore How did you run "discover unit tests"? method?

I can not find this command on the command panel nor any place ...

Thanks :)

**Comment by alexwhittemore** [comment]
In the bottom bar, bottom left, where it usually says "run tests" - I think it'll say "discovery failed" when such is the case, and clicking it will bring up the command palette with an option to discover. 
![capture](https://cloud.githubusercontent.com/assets/332827/25146680/9bc29b3e-2429-11e7-91eb-fd01c413c390.PNG)

**Comment by DonJayamanne** [comment]
@alexwhittemore  Sorry, please run the command ```Run All Unittests```

**Comment by VicLiang621** [comment]
I have a similar issue where when you click "Debug test" the running tests never stop and breakpoints do not matter. When trying to implement the `if __name__ == '__main__':
    unittest.main()`, it only breaks at that current files line and does not jump to the class method. 
![image](https://cloud.githubusercontent.com/assets/15284489/26526909/e271421e-4356-11e7-8bd4-f3c6538c7f37.png)

**Comment by sdtom** [comment]
Similar issue, my workaround.. keep clicking "debug test" over and over..  first time gets READY, second time generates an error.. but maybe 1 out of 10 times instead of just getting READY,  things turn orange and debugging works fine

**Comment by MattMorgis** [comment]
I am having the same issue with both the `unittest` and `pytest` options, both generate the same error. If you can point me in the right direction, I can get a fix merged in. 

I created a sample project to help identify the issue: https://github.com/MattMorgis/python-tests

Each time I hit `Debug Test` inline in VS Code, I get this output: 
```
FAILED (errors=1)
Traceback (most recent call last):
  File "/Users/morgism/.vscode/extensions/donjayamanne.python-0.6.9/pythonFiles/PythonTools/visualstudio_py_testlauncher.py", line 343, in <module>
    main()
  File "/Users/morgism/.vscode/extensions/donjayamanne.python-0.6.9/pythonFiles/PythonTools/visualstudio_py_testlauncher.py", line 238, in main
    enable_attach(opts.secret, ('127.0.0.1', getattr(opts, 'port', DEFAULT_PORT)), redirect_output = True)
  File "/Users/morgism/.vscode/extensions/donjayamanne.python-0.6.9/pythonFiles/PythonTools/ptvsd/attach_server.py", line 167, in enable_attach
    server.bind(address)
  File "/Users/morgism/anaconda/envs/py2Env/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
```

I am using a [conda](https://www.continuum.io/downloads) environment and have my Python path set both in `settings.json` and as an ENV variable. `pytest` is installed there when trying to run that configuration.

**Comment by DonJayamanne** [comment]
Will look into this over the weekend

**Comment by samiraguiar** [comment]
This issue still persists, at least for me on Fedora 26.
Apparently it hangs waiting for a debugger to be attached, since no timeout is passed to `wait_for_attach()` in [`visualstudio_py_testlauncher.py`](https://github.com/DonJayamanne/pythonVSCode/blob/f28167456c57dd12c7c43ac926e0cbae650c194a/pythonFiles/PythonTools/visualstudio_py_testlauncher.py#L242).

**Comment by DonJayamanne** [comment]
@MattMorgis  @samiraguiar can you try changing the port to something different such as ```3001``` or similar in your user or workspace settings (```settings.json```) as follows:   
```json
"python.unitTest.debugPort": 3000
```

**Comment by DonJayamanne** [comment]
@yRefl3x how about your self, are you still experiencing the same issue

**Comment by DonJayamanne** [comment]
@MattMorgis found a problem with your code, ```assertEqual``` needs to be qualified by ```self```
```python
class MetamapAPITest(unittest.TestCase):
    def test_one(self):
        self.assertEqual(true, false)
```

**Comment by MattMorgis** [comment]
@DonJayamanne I committed both changes to my project: adding `self` and changed debug port to `3001`. 

Looks like it lead to a new error: 
```
There was an error in starting the debug server. 
Error = 
{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3001}
```

**Comment by samiraguiar** [comment]
@DonJayamanne changing the port didn't help, the issue persisted (though no errors similar to that of @MattMorgis happened).

I'm now also getting `Error: undefined` when running [these tests](https://github.com/decalage2/oletools/blob/1b7f44d128dcb623ec27e3d042d4e3ba858470dd/tests/json/test_output.py). Here's my configuration for the linked repo:

```json
{
    "python.linting.pylintEnabled": false,
    "python.unitTest.unittestEnabled": true,
    "python.unitTest.debugPort": 3000,
    "python.unitTest.unittestArgs": [
        "-v",
        "-f",
        "-s",
        "./tests",
        "-p",
        "test_*.py"
    ],
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/*.pyc": true,
        "**/.DS_Store": true
    },
    "python.pythonPath": "/bin/python3"
}
```

**Comment by DonJayamanne** [comment]
@samiraguiar Hmm, seems to work at my end in the dev version. Will check the current released version.

**Comment by yRefl3x** [comment]
My experience got better, I can debug unittests now, but it will only work on the first or second tries (kind of inconsistent). Meaning I click the code lens (both class and method lenses work here) for debugging the first time, everything works as expected. If I click a second time after stopping debugging, "Running Tests" is displayed at the bottom indefinitely but nothing happens. To be able to debug again, I have to reload the window.
Btw, I'm now on VSCode v1.17.1 and extension v0.7.0

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#89
