### ISSUE TITLE
flake8 doesn't work

### ISSUE THREAD

**Issue by janhancic** [DonJayamanne/pythonVSCode#838]
## Environment data
VS Code version:  1.10.2
Python Extension version: 0.60
Python Version: 2.7.12
OS and version: Ubuntu 16.04

## Actual behavior
Nothing hapens when code contains lint errors

## Expected  behavior
I should get lint errors highlighted

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
n/a

Your settings.json:   
```json
"python.linting.pylintEnabled": false,
"python.linting.flake8Enabled": true,
```   
## Logs
Output from ```Python``` output panel  

there is no output

Output from ```Console window``` (Help->Developer Tools menu)

some jedi errors, but not sure that's relevant?

So my flake8 worked fine on preview channel, but I had to switch to stable as the preview got borked completely and didn't start up anymore, even after reinstalling ...

I don't know what other information to provide. But basically nothing happens ...

**Comment by Gizmotoy** [comment]
Seeing the same thing here, both on 1.10.2 and on the 1.11.0 Insiders from 3/23.  This had been working as of the previous official release, so it seems to have been broken relatively recently.

Same empty Python output panel and lack of clues in the Console Window.

Happy to provide whatever information is required to track this down.

**Comment by janhancic** [comment]
Is there any info on this?

**Comment by jingniao** [comment]
waiting for fix this

**Comment by DonJayamanne** [comment]
Please could you provide some sample code to replicate this issue.

**Comment by janhancic** [comment]
```
def bob():
    not_used = True
    return False
```

not_used should be marked as, well, not used.
What happens: nothing

**Comment by janhancic** [comment]
Is there a way to enable some extra output/debugging so we can give you more info?

**Comment by janhancic** [comment]
Just updated to latest VS Code version (v1.11.0) and it still doesn't work.

**Comment by DonJayamanne** [comment]
What version of flake8 do you have installed?

**Comment by jingniao** [comment]
os windows 7 64bit
vscode 1.11.0
python plugins of vscode version 0.6.0
system python version 2.7.13
flake8==3.3.0
when `python.linting.pylintEnabled` is `true` only, lint is ok
when `python.linting.flake8Enabled` is `true` only, lint is nothing out

**Comment by janhancic** [comment]
```
$ flake8 --version
3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2) CPython 3.5.2 on Linux
```

I ran the above from the integrated terminal.

**Comment by DonJayamanne** [comment]
Unfortunately I'm unable to replicate this at my end. 
I'll release a new version with additional logging.

**Comment by janhancic** [comment]
Thanks, I'l report back when it gets down to me. Where should I look for the logs?

**Comment by DonJayamanne** [comment]
In the console window/tab (Help -> Toggle Developer Tools)

**Comment by DonJayamanne** [comment]
Basically the Chrome developer console

**Comment by DonJayamanne** [comment]
But inside vscode

**Comment by Crazy-Owl** [comment]
I can also confirm that flake8 doesn't work and no errors are shown anywhere.

My VSCode info (just installed it today along with python extension)

Version 1.11.1
Commit d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
Date 2017-04-06T13:55:56.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

Also no syntax/other errors are highlighted anywhere (e.g. if I write an undefined variable nothing is highlighted as an error) and `Problems` tab (`Ctrl+Shift+M`) is empty at any given time.

**Comment by DonJayamanne** [comment]
I believe I have fixed this issue, please test in the latest version and let me know.
Related change https://github.com/DonJayamanne/pythonVSCode/commit/6f1ece025345c31036076d923f5341192f75d1e7

**Comment by janhancic** [comment]
Thanks, I'll report back once the new version shows up.

**Comment by janhancic** [comment]
Just updated, sadly the problem is still here. I don't see any logging in the dev tools console or anything else that would give more info.

**Comment by DonJayamanne** [comment]
Are you sure there's nothing in the dev tools console, there must be something in there.

**Comment by DonJayamanne** [comment]
@janhancic Are you using any virtual environments?

**Comment by DonJayamanne** [comment]
@janhancic 
Please could you try running the flake8 linter manually from the terminal window and letting me know what output you get (fyi - try linting a file that you've tried from within vscode).

**Comment by Gizmotoy** [comment]
I saved this as test.py (I added line numbers for clarity):
```
1: def new_function():
2:    test = 3
3:    return 0
4:
5: return new_function()
```
Running flake8 on it from the terminal, I receive:
> test.py:2:5: F841 local variable 'test' is assigned to but never used
> test.py:5:1: F999 'return' outside function
> test.py:5:22: W292 no newline at end of file

The code in VSCode is unadorned, both in the editor and minimap, with no indication of any of the above issues.

On Windows, I used the following extension config (paths are verified correct):
```
    "python.pythonPath": "c:/python27/python.exe",
    "python.linting.flake8Path": "C:/Python27/Scripts/flake8.exe",
    "python.linting.pylintEnabled": false, // Disable the default, pylint
    "python.linting.flake8Enabled": true,  // Use Flake8 (PEP8 style + Pyflakes functional)
    "python.formatting.formatOnSave": false,
```

This is native, no virtual environment.  The developer console shows nothing related to python, though I do have a few unrelated keybinding conflicts.  I'll admit I'm not 100% confident I'm looking in the right place: Help -> Toggle Developer Tools -> Console tab.

VSCode 1.11.2, Python 0.6.2

**Comment by DonJayamanne** [comment]
@Gizmotoy 
Could you run the following command from the terminal window:   
'c:/Python27/Scripts/flake8.exe' --format=%(row)d,%(col)d,%(code)s,%(code)s:%(text)s test.py

Then please provide the output here.

**Comment by janhancic** [comment]
Sorry, I've been away from the computer and now we're in the easter bank weekend. I'll try this on Tuesday when I'm back in the office. Thanks!

**Comment by DonJayamanne** [comment]
@janhancic , thanks, please try the following command: 
flake8 --format=%(row)d,%(col)d,%(code)s,%(code)s:%(text)s <file path>

**Comment by Gizmotoy** [comment]
@janhancic The command you requested:
```
c:\Users\gizmotoy\Desktop>c:/Python27/Scripts/flake8.exe --ignore=E201,E202,E203,
E211,E221,E222,E241,E251,E271,E272,E501 --format=%(row)d,%(col)d,%(code)s,%(code
)s:%(text)s test.py
2,5,F841,F841:local variable 'test' is assigned to but never used
5,1,F999,F999:'return' outside function
5,22,W292,W292:no newline at end of file
```

And the formatted version of the example above (I had removed the ignores from my setup for simplicity):
```
c:\Users\gizmotoy\Desktop>c:/Python27/Scripts/flake8.exe --format=%(row)d,%(col)d
,%(code)s,%(code)s:%(text)s test.py
2,5,F841,F841:local variable 'test' is assigned to but never used
5,1,F999,F999:'return' outside function
5,22,W292,W292:no newline at end of file
```

Then a final time again without the --format:
```
c:\Users\gizmotoy\Desktop>c:/Python27/Scripts/flake8.exe test.py
test.py:2:5: F841 local variable 'test' is assigned to but never used
test.py:5:1: F999 'return' outside function
test.py:5:22: W292 no newline at end of file
```

**Comment by janhancic** [comment]
@DonJayamanne I ran your command and got this (as expected):

```
flake8 --format="%(row)d,%(col)d,%(code)s,%(code)s:%(text)s" vault/admin_app/backend/graphql/test_utils.py
9,5,F841,F841:local variable 'not_used' is assigned to but never used
```

I get no output/errors in VS code (v1.11.2, python extension v0.6.2)

Not sure if thi sis relevant, I've got both python 2 and 3 installed on my machine, but I have set the workspace interpreter to 3.5. However python support from this extension was always spotty. I never got proper intellisense unless I create `__init__` files everywhere for example (I've tried all the ways to set the PYTHONPATH without any luck).

**Comment by janhancic** [comment]
Just FYI, I've completely removed VS Code and VS Code Insiders from my machine (app & settings). I've now installed VS Code Insiders from scratch and installed the python extension and linting now works!

However, it still does nothing in the stable release of VS Code. So either the reinstall magically fixed something somewhere, or there's a bug that has already been fixed in insiders that hasn't gotten to the stable release yet :)

**Comment by Gizmotoy** [comment]
I uninstalled and reinstalled the Insiders Edition, similiar to what @janhancic did, and had the same result.  This got me really suspicious, as I had the Insiders build installed and updated prior to uninstallation, and before I uninstalled it was not working.  It seemed like that must mean it was a settings issue, and was probably why @DonJayamanne couldn't reproduce it.

Going back to the stable build I started hunting.  I found this in the Workspace settings of every project I've opened in VSCode recently:
```
{
    "python.linting.flake8Enabled": false
}
```

Since the workspace settings override the global settings, flake8 was disabled.  What's really unusual is that I never intentionally use the Workspace settings so I have a consistent environment across all of my projects.  I don't know if it got added there without my knowledge (false is the default), or if I somehow put it there and forgot about it.  That seems unlikely over dozens of projects, but I suppose it's possible and if that's the case I apologize.

Removing that fixed the behavior in both builds, though.

**Comment by janhancic** [comment]
Sadly I don't have my old configs to confirm this. But I can say that I never used workspace settings either, so if that got added somehow I would never have noticed :(

**Comment by Gizmotoy** [comment]
But you also said the stable build is still not working for you.  It is now working for me, so there might be something else at issue in your case... or maybe that Workspace setting persisted.

**Comment by janhancic** [comment]
Yep ... checked the workspace setting and there it was ... I def didn't put it there (I would have no reason to disaable flake8 as that's the only linter we use), so I have no idea how it got there.

So I suppose the linter works fine, it's just that something is adding workspace settings?

I do hope however that @DonJayamanne didn't spend ages trying to reproduce this though :(

**Comment by DonJayamanne** [comment]
That's great news guys. I will close this issue. 
The setting gets added visa a prompt. The extension may have displayed the message indicating the linter failed and whether you would like to disable it, you may have clicked 'ok'

**Comment by Gizmotoy** [comment]
That definitely sounds like what happened.  I mentioned above at one point I was getting the error:

"Error: There was an error in running the linter 'flake8'"

and distinctly remember the box you describe.  I'm quite sure I clicked OK at one point, but kind of thought it was a "Disable for this session" or something and completely forgot about it.  I didn't realize it was changing the workspace settings.

Glad this is sorted, and sorry for prolonging the ticket.  Thanks!

**Comment by DonJayamanne** [comment]
That's alright

**Comment by keisuke-nakata** [comment]
I have the same problem.  
flake8 does not work at all.

My settings:
```
"python.linting.pylintEnabled": false,
"python.linting.flake8Enabled": true,
```

My test file (`foo.py`):
```
a = 1
b   = 1 
print(b)
```

Outputs from "Problem" tab on the panel: none
Outputs from terminal (`flake8 foo.py`): 
```
foo.py:0:1: C101 Coding magic comment not found
foo.py:2:2: E221 multiple spaces before operator
foo.py:2:8: W291 trailing whitespace
foo.py:3:9: W292 no newline at end of file
```
Outputs from developer panel console: none

Thank you in advance!

**Comment by DonJayamanne** [comment]
@keisuke-nakata 
What's the output from the ```Python``` log (tab next to ```Problems```, select ```Python``` from the dropdown)

**Comment by DonJayamanne** [comment]
@janhancic does this still persists, if it does please reopen the issue.

**Comment by aaroncraig10e** [comment]
I'm seeing this issue as well.

user settings: 
```
{
    "workbench.colorTheme": "Verdigris Light",
    "editor.tabSize": 2,
    "editor.renderWhitespace": "boundary",
    "editor.rulers": [80, 120],
    "editor.folding": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.scrollBeyondLastLine": false,
    "files.autoSave": "onFocusChange",
    "editor.minimap.enabled": false,
    "eslint.autoFixOnSave": true,
    "window.zoomLevel": 0,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.editor.enablePreview": false,
    "AllAutocomplete.minWordLength": 3,
    "atomKeymap.promptV3Features": true,
    "editor.formatOnPaste": true,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "python.formatting.formatOnSave": true,
    "python.pythonPath": "/Users/aaroncraig/.virtualenvs/${workspaceRootFolderName}/bin/python",
    "python.unitTest.unittestEnabled": true,
    "editor.fontFamily": "'Input Mono', Menlo, Monaco, 'Courier New', monospace",
    "editor.tokenColorCustomizations": {
        "comments": "#A8A8A8"        
    },
    "python.formatting.autopep8Args": ["--max-line-length=120"]
}  
```
```
flake8 --version
3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.2 on Darwin
```
Test file (test-flake.py)
```python
def main():
    unused = True

    return False
```
Flake output:
```
flake8 test-flake.py
test-flake.py:2:5: F841 local variable 'unused' is assigned to but never used
```

Nothing is marked in the editor, no output in the Python log output.

**Comment by mfour-merickson** [comment]
I am having the same issue and I have confirmed that it is NOT disabled in the workspace setting.  I think this issue was either closed prematurely, or it has returned.  

I can get flake8 to work a single time by toggling the setting (from true to false, back to true)

```
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": [ 

    ],
```

**Comment by mfour-merickson** [comment]
If I run manually in terminal, the proper errors are reported

```
~/docker/localenv/code_scripts OS-2954-clean-all-python-files-using-flake8*
❯ flake8 reader.py
reader.py:2:1: F401 'csv' imported but unused
reader.py:3:1: F401 'os' imported but unused
reader.py:4:1: F401 'shutil' imported but unused
reader.py:8:1: F811 redefinition of unused 'json' from line 5
reader.py:9:1: F401 'getpass' imported but unused
reader.py:10:1: F401 'locale' imported but unused
reader.py:13:1: E266 too many leading '#' for block comment
reader.py:16:1: E302 expected 2 blank lines, found 0
reader.py:17:3: E111 indentation is not a multiple of four
reader.py:18:3: E111 indentation is not a multiple of four
reader.py:21:7: E111 indentation is not a multiple of four
reader.py:28:5: E265 block comment should start with '# '
reader.py:29:5: E265 block comment should start with '# '
reader.py:31:3: E111 indentation is not a multiple of four
reader.py:32:3: E114 indentation is not a multiple of four (comment)
reader.py:32:3: E265 block comment should start with '# '
reader.py:33:3: E114 indentation is not a multiple of four (comment)
reader.py:33:3: E265 block comment should start with '# '
reader.py:34:3: E111 indentation is not a multiple of four
reader.py:36:1: E266 too many leading '#' for block comment
reader.py:45:3: E111 indentation is not a multiple of four
reader.py:46:3: E111 indentation is not a multiple of four
reader.py:47:3: E111 indentation is not a multiple of four
reader.py:54:5: E265 block comment should start with '# '
reader.py:55:5: E265 block comment should start with '# '
reader.py:56:5: E265 block comment should start with '# '
reader.py:58:1: E265 block comment should start with '# '
reader.py:61:1: E265 block comment should start with '# '
reader.py:68:11: E703 statement ends with a semicolon
reader.py:77:7: E111 indentation is not a multiple of four
reader.py:78:7: E111 indentation is not a multiple of four
reader.py:81:11: E703 statement ends with a semicolon
reader.py:83:8: E703 statement ends with a semicolon
```

**Comment by mfour-merickson** [comment]
Is there a way to force the extension to execute?

**Comment by DonJayamanne** [comment]
@mfour-merickson please create a new issue with the necessary details on the corresponding [Microsoft fork](https://github.com/Microsoft/vscode-python) (the extension is now maintained on that repository). I'll look into the issue from there.

**Comment by mfour-merickson** [comment]
Will do

Mike Erickson
Engineering Manager
Mfour Mobile Research
www.mfourdiy.com
