### ISSUE TITLE
Trouble removing breakpoint during debug session

### ISSUE THREAD

**Issue by gpassero** [DonJayamanne/pythonVSCode#857]
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version: 3.5
OS and version: Windows 10   

## Actual behavior
Debugger stops on breakpoints I have removed/disabled.

## Expected  behavior
Debugger doesn't stop on removed breakpoints.

## Steps to reproduce:  
-  Put a breakpoint on the code (preferably inside a for loop)
-  Start debugging and wait until the runner stops on the breakpoint
-  Remove the breakpoints
-  Continue the debugger

The problem also happens on breakpoints I add during a debugging session.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": null,
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "BreakOnSystemExitZero"
            ]
        },
```   
Your settings.json:   
```json
{
    "editor.rulers": [120],
    "python.linting.pylintArgs": [
        "--max-line-length=120"
    ],
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 120,
    "window.zoomLevel": 0,
    "files.trimTrailingWhitespace": true,
    "python.autoComplete.extraPaths": [
    ],
    "workbench.colorTheme": "Monokai",
    "workbench.iconTheme": "vscode-icons",
    "window.menuBarVisibility": "default",
    "editor.renderControlCharacters": false,
    "files.autoSave": "afterDelay"
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
@gpassero What version of Python are you using?

**Comment by gpassero** [comment]
@DonJayamanne I am using version 3.5 of Python. I updated the VS Code IDE yesterday and noticed the problem didn't occur anymore. Was it a know bug that is now solved?

**Comment by DonJayamanne** [comment]
Absolutely no idea, all I know is that I didn't fix anything.. may have been a vscode issue.
Thanks

**Comment by XFunc** [comment]
Hello,

I have the exact same problem, with up-to-date versions of VS Code and pythonVSCode. The problem has been there since I started using VS Code + pythonVSCode as a potential alternative to Visual Studio 2015 + Python Tools for Visual Studio (beginning of this year).  I was waiting for updates to solve it but after 4 months it seems that it is still there : breakpoints set either during of before debug session are correctly hit, but when I remove them the debugger still stop at the breakpoints line afterwards.

The only particular thing in my launch.json configuration is that I am using a custom (embedded) Python interpreter (based on Python-2.7.11). As I noticed code similarities between Python Tools for Visual Studio and python for VS code, it may be worth mentioning that I never faced this particular problem in the former (I have been using PTVS for some years now). 

While I could make everything else perfectly working during the last four months (debugging, code navigation through ctags, linting, ...), this problem is really the last blocking point to me for switching to VSCode :-( (VSCode + pythonVSCode may probably be the perfect setup for me because I am developping on both Windows/Linux)

Any idea ? (Please let me know if you need extra info)

Best Regards

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#98
